# Generated by Django 4.2.8 on 2023-12-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_statususer_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statususer',
            name='status_count',
        ),
        migrations.AddField(
            model_name='user',
            name='status_count',
            field=models.BooleanField(blank=True, default=None),
        ),
    ]
