# Generated by Django 4.2.8 on 2023-12-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_user_status_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='statususer',
            name='status_count',
            field=models.BooleanField(blank=True, default=None),
        ),
    ]
