# Generated by Django 4.2.8 on 2023-12-15 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_statususer_status_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statususer',
            name='status_count',
        ),
    ]
