# Generated by Django 4.2.8 on 2023-12-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_user_status_count_user_status_dcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status_dcount',
        ),
        migrations.AddField(
            model_name='statususer',
            name='status_count',
            field=models.BooleanField(blank=True, default=None),
        ),
    ]
