# Generated by Django 4.2.8 on 2023-12-15 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_delete_statususer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status_count',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.CreateModel(
            name='StatusUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
