# Generated by Django 4.2.8 on 2023-12-15 08:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_user_status_count_statususer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statususer',
            name='author',
        ),
        migrations.AddField(
            model_name='statususer',
            name='author',
            field=models.ManyToManyField(blank=True, default=None, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
