# Generated by Django 4.2.8 on 2023-12-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_statususer_author_statususer_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status_count',
        ),
        migrations.AddField(
            model_name='user',
            name='count',
            field=models.BooleanField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
