# Generated by Django 4.2.8 on 2023-12-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_user_status_count_user_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='count',
            field=models.BooleanField(default=True),
        ),
    ]
