# Generated by Django 4.2.8 on 2023-12-15 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_user_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statususer',
            name='author',
        ),
        migrations.AddField(
            model_name='statususer',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
